const mongoose = require('mongoose')


const tenderSchema = mongoose.Schema({
    title:{
        type:String,
        required:true
    },
    description:{
        type:String,
        required:true
    },
    location:{
        type:String,
        required:true
    },
    pincode:{
        type:Number,
        required:true
    },
    tenderValue:{
        type:Number,
        required:true
    },
    bidValidityDays:{
        type:String,
        required:true
    },
    periodOfWork:{
        type:String,
        required:true
    },
    contractType:{
        type:String,
        required:true
    },
    productCategory:{
        type:String,
        required:true
    },
    preQualification:{
        type:String,
        required:true
    },
    tenderId:{
        type:String,
        required:true
    },
    tenderType:{
        type:String,
        required:true
    },
    tenderCategory:{
        type:String,
        required:true
    },
    generalTecEvalAllowed:{
        type:String,
        required:true
    },
    withrawalAllowed:{
        type:String,
        required:true
    },
    paymentMethod:{
        type:String,
        required:true
    },
    tenderFee:{
        type:String,
        required:true
    },
    tenderFeeExemptionAllowed:{
        type:String,
        required:true
    },
    emdFee:{
        type:String,
        required:true
    },
    emdFeeType:{
        type:String,
        required:true
    },
    emdPercentage:{
        type:String,
        required:true
    },
    emdExmptionAllowed:{
        type:String,
        required:true
    },
    bidOpeningDate:{
        type:String,
        required:true
    },
    docuDowStartDate:{
        type:String,
        required:true
    },
    docuDowEndDate:{
        type:String,
        required:true
    },
    clarificationStartDate:{
        type:String,
        required:true
    },
    clarificationEndDate:{
        type:String,
        required:true
    },
    bidSubmitionStartDate:{
        type:String,
        required:true
    },
    bidSubmitionEndDate:{
        type:String,
        required:true
    },
    bidStatus:{
        type:String,
        enum: ['Pending', 'Open', 'Closed'],
        default:'Pending'
    },
    status:{
        type:String,
        enum: ['Pending', 'Rejected', 'Approved'],
        default:'Pending'
    },
    authorityId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'authority'
    },
    bidders:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:'bidders'
    }]
})

const tenderModel= mongoose.model('tenders',tenderSchema)

module.exports=tenderModel